export var key1test:[
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
  ]
export var key2:["cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus", "cactus"]
